// Every user-visible string. Overridden per key through
// definition.content.texts. Placeholders: {name}.
export const DEFAULT_TEXTS = Object.freeze({
  loading: "Loading diagram...",
  loadError: "Failed to load diagram image. Please check your connection and try refreshing the page.",
  initError: "Failed to initialize annotations",
  errorTitle: "Error",
  retry: "Retry",
  close: "Close",
  diagramLabel: "Diagram",

  searchPlaceholder: "Search titles, text, links...",
  searchLabel: "Search annotations",
  resetFilters: "Clear all filters",
  resultCountInitial: "Showing all annotations",
  summaryMatchOne: '{count} match for "{query}"',
  summaryMatchMany: '{count} matches for "{query}"',
  summaryAll: "Showing all annotations ({total})",
  summarySome: "Showing {count} of {total} annotations",

  levelTitle: "Level",
  levelValue: "Level {level}",
  levelMax: "max",
  noRegularTags: "No regular tags found in this diagram.",
  noTags: "No tags found in this diagram.",

  tagFilterPlaceholder: "Filter tags...",
  tagFilterLabel: "Filter tags",
  tagFilterEmpty: "No tags match the filter.",
  tagTreeReset: "Reset",
  tagTreeResetTitle: "Show all tags and clear the focus",
  tagTreeShowAll: "Show all",
  tagTreeShowAllTitle: "Show all tags",
  tagTreeHideAll: "Hide all",
  tagTreeHideAllTitle: "Hide all tags",
  tagTreeInvert: "Invert",
  tagTreeInvertTitle: "Invert which tags are hidden",
  tagTreeCount: "{count} tags",
  tagTreeHiddenSuffix: " · {hidden} hidden",
  tagTreeHiddenBelow: "{count} hidden",
  tagTreeExpand: "Expand {path}",
  tagHiddenBy: "Hidden by {ancestor}. Show {ancestor} to change this.",
  tagShowBranch: "Show {path} and everything under it",
  tagHideBranch: "Hide {path} and everything under it",
  tagFocus: "focus",
  tagSelect: "select",
  tagSelectOn: "Select {path} (tag picker)",
  tagSelectOff: "Deselect {path}",
  elementCountOne: "{count} element",
  elementCountMany: "{count} elements",

  hiddenTagsAndLevel: "Hidden because tags {tags} are filtered out and level-{recordLevel} is above selected level-{selectedLevel}.",
  hiddenLevel: "Hidden because level-{recordLevel} is above selected level-{selectedLevel}.",
  hiddenUnknownTags: "Hidden because one or more required tags are filtered out.",
  hiddenTag: 'Hidden because tag "{tag}" is filtered out.',
  hiddenTags: "Hidden because tags {tags} are filtered out.",
  currentlyHidden: "currently hidden",

  resultsLabel: "Diagram explanations",
  resultFallbackTitle: "Help",
  resultFallbackBody: "Help annotation",
  ariaTags: "tags {tags}",
  ariaLevel: "level {level}",
  ariaPinned: "pinned",
  pin: "Pin",
  unpin: "Unpin",
  pinnedHeader: "Pinned ({count})",
  pinnedShow: "Show",
  pinnedHide: "Hide",
  pinnedClear: "Clear",
  matchesDivider: "Matches",
  noMatchesTitle: "No matches",
  noMatchesBody: "Try another search term.",

  themeDark: "Dark theme",
  themeLight: "Light theme",
  themeToDark: "Switch to dark mode",
  themeToLight: "Switch to light mode",
  themeToggle: "Toggle dark mode",
  userAnnotations: "User Annotations",
  userAnnotationsTitle: "Manage user annotations",
  exitEdit: "exit edit",
  exitEditTitle: "Exit edit mode",
  closePanel: "Close filter panel",
  openPanel: "Open filter menu",
  aboutButton: "About this diagram",
  aboutTitle: "About",

  shortcutsTitle: "Keyboard shortcuts",
  shortcutSearch: "Focus search",
  shortcutPan: "Pan (hold {shift} to pan far)",
  shortcutZoom: "Zoom in / out",
  shortcutFit: "Fit the whole diagram",
  shortcutHelp: "Open these controls",
  shortcutClose: "Close",
  linksTitle: "Links",
  paramsTitle: "URL parameters",
  linkCurrent: "Current",
  linkCurrentDescription: "Exactly this view: position, filters, pins and notes",
  linkNoAnnotations: "Without annotations",
  linkNoAnnotationsDescription: "The same view, leaving out {annotations}",
  linkNoPosition: "Without position",
  linkNoPositionDescription: "The same view, opening on the whole diagram",
  linkNoHiddenTags: "Without hidden tags",
  linkNoHiddenTagsDescription: "The same view, with {tags} shown again",
  linkClean: "Clean",
  linkCleanDescription: "Just the diagram, as it opens by default",
  linkCopy: "Copy",
  linkOpen: "Open",
  linkOpenTitle: "Load this link here",
  linkCopied: "Copied",
  linkCopyFailed: "Copy failed",
  linkCopyUnavailable: "Copy unavailable",
  noParams: "No parameters: the diagram opens as it does by default.",
  unknownParam: "Not used by the diagram",
  paramNone: "none",
  paramLeftOut: "Parameter left out",
  paramInvalid: "Not a valid value",
  paramOneOf: "one of",
  paramAnyOf: "any of",
  paramEmpty: "(empty)",
  paramBlob: "{annotations}, {chars} chars",
  copySlide: "Copy as slide",
  copySlideDescription: "Reveal.js section with this view",

  annotationsModalTitle: "User Annotations",
  addAnnotation: "Add New Annotation:",
  titleOptional: "Title (optional):",
  modeLabel: "Mode:",
  modePoint: "Point",
  modePointTitle: "Point Annotation",
  modeArea: "Area",
  modeAreaTitle: "Area Annotation",
  modeArrow: "Arrow",
  modeArrowTitle: "Arrow: click the tail, then the head",
  shapeLabel: "Shape:",
  shapeRectangle: "Rectangle",
  shapeCircle: "Circle",
  typeLabel: "Type:",
  descriptionLabel: "Description (supports HTML):",
  allowedHtml: "Allowed HTML tags: {tags}",
  previewLabel: "Preview:",
  placeAnnotation: "📍 Place Annotation",
  currentAnnotations: "Current annotations (",
  editModeToggle: "Edit Mode (enable drag & drop)",
  shareUrl: "📋 Copy Share URL",
  shareCopied: "✓ Copied!",
  shareFailed: "Failed to copy",
  clearAll: "🗑️ Clear All",
  editAnnotationTitle: "Edit Annotation",
  saveChanges: "Save Changes",
  cancel: "Cancel",
  noDescription: "No description",
  noUserAnnotations: "No user annotations yet.",
  untitled: "Untitled",
  editAction: "Edit",
  deleteAction: "Delete",
  confirmDelete: "Delete this annotation?",
  confirmClearAll: "Are you sure you want to remove all user annotations?",
  maxAnnotations: "Maximum {max} user annotations allowed.",
  kindPoint: "Point",
  kindArea: "Area",
  kindArrow: "Arrow",

  // The help dialog (footer "?" and the ? key).
  helpTitle: "Help and info",
  helpButton: "Help and info",
  helpTabOpen: "Open diagram",
  helpTabAbout: "About",
  helpTabLinks: "Share",
  helpTabUrl: "URL parameters",
  helpTabShortcuts: "Controls",
  helpTabSettings: "Settings",
  helpLinksIntro: "Each link opens this diagram in a given state. Send one to a colleague, bookmark it, or put it in a document.",
  shareViewTitle: "Link to this view",
  shareDiagramTitle: "The diagram",
  sharePresentationTitle: "For presentations",
  helpUrlIntro: "The address of this page describes what you see, and follows along as you move, filter and pin. All parameters are optional.",
  paramCurrentTitle: "In this address",
  paramReference: "All parameters",
  paramGroupView: "View",
  paramGroupNotes: "Notes",
  paramGroupInterface: "Menu",
  paramGroupFilters: "Filters",
  paramGroupFocus: "Pins and highlights",
  paramGroupDiagram: "Diagram",
  paramGroupDevelopment: "Development",
  paramGroupOther: "Other",
  focusTagOn: "Focus on {path}",
  focusTagOff: "Stop focusing on {path}",
  focusTagHidden: "Hidden topics cannot be in focus",
  tagTreeDimOthers: "Dim others",
  tagTreeDimOthersTitle: "Dim everything but the topics in focus",
  tagTreeDimOthersNoFocus: "Focus on a topic first",
  aboutVersion: "Version",
  aboutLicense: "License",
  aboutMaintainer: "Maintainer",
  aboutSource: "Source",
  aboutIssues: "Report an issue",
  aboutBuiltWith: "Built with",
  downloadsTitle: "Download the diagram",
  downloadAction: "Download",
  downloadDrawioTitle: "draw.io original",
  downloadDrawioDescription: "Opens and can be edited in draw.io. A few details drawn by this page are missing, such as the translucent traffic bands the legend refers to.",
  downloadFullTitle: "Full diagram",
  downloadFullDescription: "Everything, as it looks without filters, bands included. Does not open in draw.io.",
  downloadViewTitle: "This view",
  downloadViewDescription: "What you see now: the level and topics you chose, your search, pins and notes. Does not open in draw.io.",
  downloadViewFailed: "Could not save this view",
  controlsPointer: "Mouse and touch",
  controlsKeyboard: "Keyboard",
  ctlZoom: "Zoom",
  ctlZoomHow: "Scroll wheel, or pinch",
  ctlPan: "Move around",
  ctlPanHow: "Drag",
  ctlHelp: "Read what a part is",
  ctlHelpHow: "Hover over it, or tap it",
  ctlPin: "Pin a part, to find it again or share it",
  ctlPinHow: "Pin, in its explanation",
  ctlMenu: "Search, and filter by detail level and topic",
  ctlMenuHow: "The menu button, bottom right",
  shortcutTabs: "Switch tabs in this dialog",
  shortcutPickTag: "Tag picker mode: select the topic marked [1], [2], … in the open tooltip",
  shortcutPickUndo: "Tag picker mode: undo, redo",
  metaBuiltWith: "Built with",
  metaUserGuide: "User guide",

  // Settings tab and tag picker mode.
  settingsIntro: "Settings that change how the diagram behaves. Each one is part of the address, so a link keeps it.",
  tagPickerSetting: "Tag picker mode",
  tagPickerSettingDescription:
    "For working out which topics a view (a slide, say) should show. Hover a part of the diagram and click its topics to select them (or press its number; the search field then gives up the keyboard), or use select in the menu's tag tree. Selected parts glow magenta, the focus glows yellow. The menu gets a bar to focus, show or hide the selected topics. Levels and priorities are left alone. Make final turns the mode off and takes it out of the address; the focus and hidden topics stay.",
  tagPickerUnavailable: "Needs a mouse or trackpad: not available on touch screens.",
  debugSettingTitle: "Debug",
  debugSettingDescription:
    "Reloads the page with ?debug: loads the diagram's debug source (source.debug) if it has one, reports missing and duplicate data-slug values in the browser console, and shows Copy as slide on the Share tab.",
  debugOpen: "Open in debug",
  debugLeave: "Leave debug",
  tagPickerTitle: "Tag picker",
  tagPickerCount: "{count} selected",
  tagPickerEmpty: "Hover a part of the diagram and click its topics, or use select in the tree.",
  tagPickerTooltipLabel: "Select",
  tagPickerClear: "Clear selection",
  tagPickerClearTitle: "Deselect every topic, to pick the next ones",
  tagPickerUndo: "↶ Undo",
  tagPickerRedo: "↷ Redo",
  tagPickerUndoTitle: "Undo: {what} (Ctrl/⌘+Z)",
  tagPickerRedoTitle: "Redo: {what} (Ctrl/⌘+Shift+Z)",
  tagPickerNothingToUndo: "Nothing to undo",
  tagPickerNothingToRedo: "Nothing to redo",
  historySelection: "selection",
  historyHidden: "hidden topics",
  historyFocus: "focus",
  historyLevel: "level",
  tagPickerFocus: "Focus selected",
  tagPickerFocusTitle: "Put the selected topics in focus, without moving the view",
  tagPickerUnfocus: "Unfocus selected",
  tagPickerUnfocusTitle: "Take the selected topics out of the focus, without moving the view",
  tagPickerShow: "Show selected",
  tagPickerShowTitle: "Show the selected topics, with their parents and children; everything else stays as it is",
  tagPickerHide: "Hide selected",
  tagPickerHideTitle: "Hide the selected topics and everything under them",
  tagPickerHideOthers: "Hide others",
  tagPickerHideOthersTitle: "Show only the selected topics, with their parents and children, and hide every other topic",
  tagPickerFinal: "Make final",
  tagPickerFinalTitle: "Check the result, then turn tag picker mode off",
  finalDialogTitle: "Make final",
  finalIntro: "Turns tag picker mode off and takes tag-picker-mode out of the address. The hidden topics, focus, level and position stay as they are.",
  finalResult: "The result",
  finalTopics: "Topics shown",
  finalTopicsValue: "{shown} of {total}",
  finalHidden: "Hidden",
  finalFocus: "In focus",
  finalFocusDim: "{tags} (dim others)",
  finalLevel: "Level",
  finalLevelValue: "{level} of {max}",
  finalLevelMax: "max",
  finalParts: "Parts shown",
  finalSearch: "Search",
  finalPins: "Pins",
  finalNone: "none",
  finalChecks: "Check",
  finalIdle: "Selected, but neither in focus nor hidden: {tags}. The selection itself does nothing in the final view.",
  finalSelectedHidden: "Selected and hidden: {tags}.",
  finalEverything: "Nothing is hidden and nothing is in focus: the view shows the whole diagram.",
  finalSearchFilters: 'The search "{query}" also filters the view.',
  finalAllGood: "Every selected topic is in focus or hidden.",
  finalNoUndo: "This cannot be undone: the selection and the undo history are gone afterwards. Copy the backup link first to come back to it.",
  finalCopyBackup: "Copy backup link",
  finalCopyBackupTitle: "This address as it is, with tag picker mode and the selection",
  finalCopyFinal: "Copy final link",
  finalCopyFinalTitle: "The address after Apply, without tag picker mode",
  finalApply: "Apply",

  // Local mode (no diagram in the definition).
  localTitle: "Open a diagram",
  localIntro: "diagram-webkit shows a draw.io SVG as an interactive diagram: search its help text, filter by tags and detail level, pin, highlight and share exactly what you see. Diagrams with tags and help text get the most out of it.",
  localPrivacy: "Nothing leaves this browser. The diagram is never uploaded or sent to a server; the only request is to a link you choose to open.",
  localProject: "diagram-webkit on GitHub",
  localGuide: "User guide",
  localChoose: "Choose SVG file…",
  localDrop: "or drop an SVG anywhere on the page",
  localUrlLabel: "or load it from a link",
  localUrlPlaceholder: "https://example.org/diagram.svg",
  localUrlLoad: "Load",
  localCancel: "Cancel",
  localDropHere: "Drop the SVG to open it",
  localNotSvg: "{name} is not an SVG file.",
  localLinkFailed: "Could not load {url}: {reason}",
  localDecodeFailed: "The diagram in this link could not be read: {reason}",
  localReadFailed: "Could not open {name}: {reason}",
  localTooLargeToKeep: "This diagram ({size}) is too large to keep across the restart. Open the file again after reloading.",
  localOpenAnother: "Open another diagram…",
  linkCurrentWithDiagram: "Exactly this view, the diagram itself included",
  embedInside: "The diagram is inside these links ({size}), after #, which is never sent to a server.",
  embedLong: "Long links ({size}, {count} characters): some chat tools and mail clients cut links this long.",
  embedVeryLong: "Very long links ({size}, {count} characters): many tools will cut or reject them. Sharing the SVG file may work better.",
  embedTooLarge: "The diagram ({size}) is too large to put in a link, so these links open without it. Share the SVG file instead.",
  embedLoadedFrom: "These links open the diagram from {url}; the diagram itself is not in them.",
  embedDownload: "Download SVG",
});

export type TextKey = keyof typeof DEFAULT_TEXTS;
export type Texts = Readonly<Record<TextKey, string>>;

export function resolveTexts(overrides: Readonly<Record<string, string>> | undefined): Texts {
  const unknown = Object.keys(overrides || {}).filter((key) => !(key in DEFAULT_TEXTS));
  if (unknown.length > 0) {
    throw new Error(`content.texts: unknown keys ${unknown.join(", ")}`);
  }
  return Object.freeze({ ...DEFAULT_TEXTS, ...(overrides || {}) });
}

export function formatText(template: string, vars: Readonly<Record<string, string | number>> = {}): string {
  return template.replace(/\{(\w+)\}/g, (match, name: string) =>
    Object.prototype.hasOwnProperty.call(vars, name) ? `${vars[name]}` : match,
  );
}
